name: rclone sync gs://cmip6 s3://cmip6-pds
on:
  # runs 4x daily at 0,6,12,18:00 UTC
  schedule:
    - cron: "0 */6 * * *"
jobs:
  rclone:
    runs-on: ubuntu-latest
    steps:
      - name: rclone - Google to S3
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          # exclude CSV and JSON catalog files, use checksums instead of mod-times, verbose output
          args: "sync --exclude /*.csv* --exclude /*.json* -c -v --transfers 45 --checkers 50 gs:cmip6 s3:cmip6-pds"
