name: rclone sync
on:
  push:
    branches:
      - master
  # runs 4x daily at 0,6,12,18:00 UTC
  #schedule:
  #  - cron: "0 */6 * * *"
jobs:
  CMIP:
    runs-on: ubuntu-latest
    steps:
      - name: rclone - Google to S3
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          # CMIP excluding NCAR/IPSL
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --filter '- /CMIP/{NCAR,IPSL}/**' --filter '+ /CMIP/**' --filter '- *' --transfers 15 --checkers 65"			 
  ScenarioMIP_NCAR_IPSL:
    runs-on: ubuntu-latest
    steps:
      - name: rclone - Google to S3
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          # ScenarioMIP and NCAR/IPSL from CMIP
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --include /ScenarioMIP/** --include /CMIP/{NCAR,IPSL}/** --transfers 15 --checkers 65"
  remainder:
    runs-on: ubuntu-latest
    steps:
      - name: rclone - Google to S3
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          # remainder of directories left untouched
          args: "sync -c -v gs:cmip6 s3:cmip6-pds --exclude /{CMIP,ScenarioMIP}/** --exclude /*.* --transfers 15 --checkers 65"
