name: rclone sync
on:
  push:
    branches:
      - master
  # runs 4x daily at 0,6,12,18:00 UTC
  #schedule:
  #  - cron: "0 */6 * * *"
jobs:
  most of CMIP:
    runs-on: ubuntu-latest
    steps:
      - name: rclone - Google to S3
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          # exclude CSV and JSON catalog files, use checksums instead of mod-times, verbose output
          args: sync -c -v gs:cmip6 s3:cmip6-pds --filter "- /CMIP/{NCAR,IPSL}/**" --filter "+ /CMIP/**" --filter "- *" --transfers 15 --checkers 65 --dry-run
					 
  ScenarioMIP and parts of CMIP:
    runs-on: ubuntu-latest
    steps:
      - name: rclone - Google to S3
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          # exclude CSV and JSON catalog files, use checksums instead of mod-times, verbose output
          args: sync -c -v gs:cmip6 s3:cmip6-pds --include /ScenarioMIP/** --include /CMIP/{NCAR,IPSL}/** --transfers 15 --checkers 65 --dry-run

  all remaining directories:
    runs-on: ubuntu-latest
    steps:
      - name: rclone - Google to S3
        uses: wei/rclone@v1.1.1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS }}
        with:
          # exclude CSV and JSON catalog files, use checksums instead of mod-times, verbose output
          args: sync -c -v gs:cmip6 s3:cmip6-pds --exclude /{CMIP,ScenarioMIP}/** --exclude /*.* --transfers 15 --checkers 65 --dry-run
